---
title: "presentation-code"
author: "Six-Thirty-Eight"
date: "12/13/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#install.packages(c("infer","countrycode","tmap", "plotly", "gridExtra"))
library(infer)
library(tidyverse)
library(countrycode)
library(gridExtra)
library(broom)
library(knitr)
library(plotly)
library(tmap)
library(gifski)
library(sf)
library(gganimate)
```

## Load data

```{r load-data-and-initialization, message = F, warning = F}
load("../data/african_gdps.RData")
data("World")

World <- World %>%
  rename(cc3 = iso_a3)
```
## EDA for Presentation

```{r gganimate-gdp-over-time}
p <- african_gdps %>%
  filter(!is.na(gdp)) %>%
  mutate(
    year = as.integer(year)
  ) %>%
  ggplot(aes(x = gdp, fill = region)) +
  geom_histogram(bins = 50)
p <- p + 
  transition_time(year) +
  labs(title = "African GDP Distribution",
       subtitle = "Year: {frame_time}",
       x = "Billions USD") + 
  view_follow(fixed_y = T)

anim_save("gdp_over_time.gif", p)
```

```{r derivative-country-percentchange}

african_gdps <- african_gdps %>%
  group_by(country) %>%
  mutate(
    percentchange_gdp = (gdp - lag(gdp, default = gdp[1]))/gdp,
    percentchange_cpi = 
      (
        inflation_annual_cpi -
          lag(inflation_annual_cpi,default = inflation_annual_cpi[1])
      )
    /inflation_annual_cpi
  ) %>%
  filter(is.finite(percentchange_cpi))

```

```{r add-map}

african_gdps <- african_gdps %>%
  mutate(
    percentchange_cpi = round(percentchange_cpi, 3)
  )

african_sf <- merge(World, african_gdps, by = "cc3")

tmap_mode("view")

africa_map <- tm_shape(filter(World, continent == "Africa")) +
  tm_borders("gray", lwd = 0.1) +
  tm_shape(african_sf) +
  tm_facets(along = "year", free.scales.symbol.size = FALSE) +
  tm_polygons(col = "percentchange_cpi", style = "cont", legend.show = F) +
  tm_text(text = "percentchange_cpi", size = 0.4)


tmap_animation(africa_map, filename = "../presentation/cpi_over_time.gif",  width = 800)

```
```{r}
data(World, metro)

m2 <- tm_shape(World, simplify = 0.5) +
          tm_fill() +
      tm_shape(metro) + 
          tm_bubbles(size = paste0("pop", seq(1970, 2030, by=10)),
          		   col = "purple",
          		   border.col = "black", border.alpha = .5,
          		   scale = 2) +
      tm_facets(free.scales.symbol.size = FALSE, nrow=1,ncol=1) + 
      tm_format("World", scale=.5)

tmap_animation(m2, filename="World population.gif", width=1200, delay=100)
```
This is some text